### PR TITLE
Purgelog Fixes

### PR DESCRIPTION
**Pull request by smg6511**
This PR solves issues with the ability to bulk purge/delete selected log entries, as well as searching log entries. Currently these features do not work at all due to:
- The purge logs processor was incorrectly supplying a full query object to the removeCollection method, rather than a simple array of where criteria
- The getlist processor specified a non-existent column name for the search query
- The feature to delete selected logs was correctly implemented on the processor side, but not on the ExtJS side

A handful of UI enhancements were also made, including:
- Disabling context menu item(s) when they are not applicable (for example, disable the Delete Selected Log Entry item when no selections have been made)
- Grid context menu now also allows deletion of selected row's log item
- Title casing of menu and action items
- Added number of logs that will be deleted to confirm message
- Remove reserved space for context menu item icons
 
Note these fixes were tested on both MODX 2.8.3 and 3.0.0-alpha3.

Also, I did not intend for the package.json file to be included in the PR. I made some changes to it for my own dev environment.

### CODE REVIEW

**Comment by Jako** [comment]
> The purge logs processor was incorrectly supplying a full query object to the removeCollection method, rather than a simple array of where criteria

There are two ways to add criteria to a query. One is using modx->newQuery. The other is a direct array. Both are correct.

**Comment by smg6511** [comment]
Bottom line is that it does not work as written right now, which is why I proposed a fix.

**Comment by Jako** [comment]
Thanks, you were right with the criteria.

**Comment by smg6511** [comment]
Glad to help!

**Pull request merged**
